.\" Manpage for noisecirkuit.
.\" Contact info@thefirstkube.net for comments or help.
.TH man 1 "May 2022" "1.0.0" "noisecirkuit man page"
.SH NAME
noisecirkuit \- simple hello world example application
.SH SYNOPSIS
noisecirkuit
.SH DESCRIPTION
noisecirkuit is a simple test application to show how to build a C++ example project with Autotools for multiplatform compilation and use.
.SH OPTIONS
noisecirkuit does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Apostolos (info@thefirstkube.net)
